### ISSUE TITLE
modify and fix

### ISSUE THREAD

**Issue by anzaikk** [chuchu0101/SoftwareEngineeringClass#1]

**Comment by chuchu0101** [comment]
I don't think I need anything but money, haha


---Original---
From: "anzaikk(john ***@***.***&gt;
Date: Wed, Jun 9, 2021 01:28 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [chuchu0101/SoftwareEngineeringClass] modify and fix (#1)




 
I think I will have time to change the code I wrote half a year ago in the summer vacation, although I can't log on this account now
